### ISSUE TITLE
Error with group policy

### ISSUE THREAD

**Issue by Pesegato** [FibreFoX/javafx-gradle-plugin#102]
My admin has set the group policy so that no executable can be run on the folder \\\appdata\local (because this is a common place for virus to start infecting).

As a consequence, my builds are broken with this message:

    Using custom package resource [application icon]  (loaded from package/windows/app.ico)
    Running [C:\Users\me\AppData\Local\Temp\iconswap507951694585685004.exe, C:\Users\me\AppData\Local\Temp\fxbundler3543723879696347773\windows\app.ico, C:\Users\me\Documents\app\build\jfx\native\app\app.exe]
    Exception: java.io.IOException: Cannot run program "C:\Users\me\AppData\Local\Temp\iconswap507951694585685004.exe": CreateProcess error=1260, program cannot be run because of group policy. Contact the administrator

To avoid this, there should be an option to set where the build process should run

**Comment by FibreFoX** [comment]
First of all: this is a really stupid way of trying to defend against some virus infection ;) and it is supposed to break a lot of things. But discussing this is out of scope of this issue 😺 

By setting `buildRoot` inside `bundleArguments` makes it possible to move any stuff. But this only works for working-things for the bundler ... the icon-swapping tool on the other hand does NOT respect this location:
```java
        //Update branding of exe file
        if (REBRAND_EXECUTABLE.fetchFrom(p) && getConfig_AppIcon(p).exists()) {
            //extract helper tool
            File iconSwapTool = File.createTempFile("iconswap", ".exe");
            iconSwapTool.delete();
            IOUtils.copyFromURL(
                    WinResources.class.getResource(TOOL_ICON_SWAP),
                    iconSwapTool);
            iconSwapTool.setExecutable(true, false);
            iconSwapTool.deleteOnExit();
```

Therefor I can't do anything.

Since JDK 9 this has been changed, but there is no support of this plugin, because of some bug inside the JDK (which seems to be fixed with JDK 10).

**Comment by FibreFoX** [comment]
To document, this should be a "can't fix" instead of "wontfix", but the result is the same: I cant do anything here, so this wont be fixed.
