### ISSUE TITLE
Can this plug in/javafxpackager sign an MSI?

### ISSUE THREAD

**Issue by pupeno** [FibreFoX/javafx-gradle-plugin#114]
I found this issue regarding signing the Mac OS version of the app:

https://github.com/FibreFoX/javafx-gradle-plugin/issues/56

but I'm working for Windows. I found a few mentions on javafxpackager documentation of how one should sign the MSI, but no details on how to do it, no details on how to specify the key/certificate.

Is this possible?

**Comment by FibreFoX** [comment]
This is out of scope of this plugin, mostly because signing happens after creating the MSI-file. "Signing" only is for JAR-files, not the native installers themselves.
Something like this might work: https://pevma.blogspot.de/2014/02/signing-windows-installation-msi.html or https://howdididothatthingagain.blogspot.de/2013/02/burn-02-how-to-sign-msi-packages-and.html
