### ISSUE TITLE
work with FXLauncher

### ISSUE THREAD

**Issue by MrVlad001** [FibreFoX/javafx-gradle-plugin#120]
HI, @FibreFoX .
I'm using your plugin in my project and it works fine. When I had a question with updating the application, I found an excellent launcher [FXLauncher](https://github.com/edvin/fxldemo-gradle) for JavaFX applications. The problem is that their native installer generator has too few parameters that I need which are available in **javafx-gradle-plugin**. Is it possible to use **javafx-gradle-plugin** and **fxlauncher** in a bundle?
Thanks

**Comment by FibreFoX** [comment]
Hi @MrVlad001 , sorry to tell but this is not compatible, this is one of the reasons why I'm working on https://github.com/FibreFoX/distribution-bundle-plugin-for-maven (and its gradle equivalent).

The `javafx-gradle-plugin` is a wrapper around the `javapackager`, which is creating it's own files, even re-creating the native files when creating each installer (instead of just using the already created ones). There are a lot of problems inside the official tooling from the JDK, so there is no support for this.

**Comment by MrVlad001** [comment]
@FibreFoX what do you think about this [decision?](https://github.com/edvin/fxlauncher/issues/41#issuecomment-268549119)
