### ISSUE TITLE
Missing bin/java in Java.runtime

### ISSUE THREAD

**Issue by marius-m** [FibreFoX/javafx-gradle-plugin#123]
Hi, 

First of all, thanks so much for the great effort. Pitty, that will have to search for alternatives for packaging project. 

Anyhow, I have a problem when bundling with old java8. Whenever its bundling jre together, the bin folder is missing (thus, resulting in trying to load with java9/10 which just goes badly). 

I so other tickets with this, but could not find the answer, nor any ideas looking through the code. Sorry if this is a duplicate. 

This happens on macos 10.13.4, java "1.8.0_172". Bundling project before did not have any problems.

**Comment by FibreFoX** [comment]
Hm ... that sounds odd. Can you try to provide something reproducable?

**Comment by marius-m** [comment]
Hm good point, I'll try to recreate it with test project and get back.

**Comment by marius-m** [comment]
So I've managed to assemble to test project: https://github.com/marius-m/javafx-packaging

### More info
It's a clean project that does not contain anything beside JavaFx and Bundler. 
When running `./gradlew jfxNative` will correctly assemble and bundle up everything, when when navigating to `..build/jfx/native/javafx-packaging-1.0-SNAPSHOT.app/Contents/PlugIns/Java.runtime/Contents/Home` will contain:
```
COPYRIGHT
LICENSE
README.html
THIRDPARTYLICENSEREADME-JAVAFX.txt
THIRDPARTYLICENSEREADME.txt
bundle/
jre/
release
```
And inside `jre` contains: 
```
COPYRIGHT
LICENSE
README
THIRDPARTYLICENSEREADME-JAVAFX.txt
THIRDPARTYLICENSEREADME.txt
Welcome.html
lib/
```
As far as I know, it should contain also `bin/java` inside the `jre` folder. And it did for quite some time, maybe something has changed in newer 1.8 version ?

Java version: 
```
$java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```
### Rant mode
I'm also running `getdown` project (https://github.com/threerings/getdown) for updating with the newest version, that searches for bundled up `jre`, and its that file that it is searching to figure if the runtime is packed together. I believe this is correct, unless something has changed.

**Comment by FibreFoX** [comment]
That sounds really strange, looking at the bundler-code the runtime is copied from "java.home"-property-location:
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/a17798f5e35c/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#l219 ... which does copy recursive: http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/a17798f5e35c/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#l607

But there is a special rule, which does restrict the bin-folder from being copied: http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/a17798f5e35c/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#l989

This makes sense, as the JVM is not started by some CLI tool, but rather by loading the JVM-library inside the native launcher via native ways. Which means, it is totally normal that this `bin`-folder is not copied.

Why do you consider this a bug? Does your application not work or anything like that, or was ist because of the getdown-module?

**Comment by marius-m** [comment]
Right now whenever app is being opened, it is being "piped" through `getdown` library which checks if there is a local jre to be used together. As the "bin" folder is missing, app is being loaded with local jre which fails when used with java9 and java10. 

Probably I'll have to see this through and look how to change the "getdown" library to check for more things if there is a local runtime there. 

Thanks alot for the effort to look into things, I think I'll take it from here!

**Comment by FibreFoX** [comment]
To switch between local installed or "packaged" JRE just change the configuration inside the `.cfg`-file of the native app bundle, dont know if this still works for JDK9+. Hopefully you get it working ;) good luck
