### ISSUE TITLE
Ability to create a 32-bit native Windows installer on 64-bit Windows OS

### ISSUE THREAD

**Issue by Hospes** [FibreFoX/javafx-gradle-plugin#22]
Hi,
Firstly I want say that you did a very cool and powerful job. Thank you very much.

Regarding my question. The problem is that my build machine has Windows 10 (64-bit). And when I'm trying to prepare windows installer with jfxNative command it's prepares .exe installer and everything is fine. But when I try to install and run my app on 32-bit Windows - I see error:

> CreateProcess failed; code 216.
> This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

Also I found next links:
https://bugs.openjdk.java.net/browse/JDK-8091056
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/81

As I understood from last link that guys somehow solved it by setting some configurations, can we do the same in gradle javafx plugin?

**Comment by FibreFoX** [comment]
Hi @Hospes , thanks for using this gradle-plugin :smile:, but I feed sad to tell you, that you NEED to have a separate development-platform for each OS/architecture you are targeting. Like mentioned inside the JDK-bug, it is a problem about their distribution-pipeline.

Quoting [the official oracle documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html)
> 7.1 Introduction
> From the standpoint of process, producing a self-contained application package is similar to producing a basic application package as discussed in Chapter 5, "Packaging Basics," with the following differences:
>     (...)
> *    Operating system and tool requirements must be met to be able to build a package in a specific format.
>
>     (...)
>
> 7.2 Benefits and Drawbacks of Self-Contained Application Packages
>     (...)
> Self-contained application packages have the following drawbacks:
> * Package per target platform  
> Self-contained application packages are platform-specific and can only be produced for the same system on which you build. To deliver self-contained application packages on Windows, Linux, and OS X, you must build your project on all three platforms.


Please keep in mind, that "Operating system and tool requirements" does count for architecture (32bit/64bit) too.

**This is no bug/missing-feature of the javafx-gradle-plungin nor the javafx-maven-plugin, it is a design-flaw of the whole packager-self-containing-concept made by oracle.**

To "workaround" this, you may want to use virtual machines instead of real machines (maybe using [Jenkins](https://github.com/jenkinsci/jenkins) or different tools having remote-build-nodes)

**Comment by Gr1ver** [comment]
Hi @FibreFoX, @Hospes !
I'am faced with the same problem, and as far as here is not mentioned any simple solutions for those who targeting one OS but both bit versions, i want to share with my experience in that. 
So, as already mentioned the javafx-gradle\maven-plugin is not responsible for bits of executable, it depends on bits of jdk used for execution of gradle. The simpliest solution to build two bit versions that i found is to run jfxNative twice, where the first run to get bundle with bits of your default jdk runtime used for gradle and the second if for opposite bits version. Gradle allows you to provide "_org.gradle.java.home_"  property in _gradle.properties_ file and also you can pass it to gradle execution command. In my case there is jdk7 as system default, jdk8x64 specified using "_org.gradle.java.home_" in _gradle.properties_ file and for jdk8x32 i run _gradle jfxNative -Dorg.gradle.java.home="my_jdk8x32_path"_.

I'm having win7x64 installed on my dev.machine, where i successfully run my project's installer and x64 executable and also i test x32 bit version on another machine with win10x32 and all works fine.

**Comment by FibreFoX** [comment]
Hi @Gr1ver , thanks for sharing that trick ... didn't knew about that way to manipulate gradle (as I'm more a maven-guy)
