### ISSUE TITLE
jfxJar task should have configurable input

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#26]
This: https://github.com/FibreFoX/javafx-gradle-plugin/blob/master/examples/javafx-proguard-gradle/build.gradle#L68

...is an ugly hack.  

It is bad form to have the obfuscated jar file overwrite the unobfuscated jar file.  

Why?  Because of Gradle's optimization of not running tasks when the inputs didn't change.  By replacing the original jar file with the obfuscated one the jar file is alway different from what the jar task produced.  That means that the jar task must always run because the output file won't match what it produced previously.

Instead the jfxJar should allow for the input to be specified so when using an obfuscator it can be configured operate on the obfuscated jar file.

**Comment by FibreFoX** [comment]
> Because of Gradle's optimization of not running tasks when the inputs didn't change.

Current implementation of this plugin does always run, so you won't have any benefit of that optimization. To reduce false-positives, and because the bundling-process might change in cause of modified customizable installer-scripts (like for innosetup), I have no good detection of any changes here.

Having the jfxJar-task being configurable seems a valid feature-request tho, but will be implemented as optional with current behaviour as fallback (don't like the idea of failing the build, because wrong file-output).

**Comment by swpalmer** [comment]
I agree that the default should be to pick up the jar task output.

It seems the default task inputs for the packager should be known... e.g. the jar and src/main/deploy/**  

But even if the packaging part always runs, at least having jfxJar input configurable will prevent the need to have the jar task always run.

**Comment by FibreFoX** [comment]
Hi there,

I have introduced a new property called `alternativePathToJarFile` and updated the proguard-example. This changes are not available as `-SNAPSHOT`-version nor on maven-central, because I'm going to implement some other things before releasing a new version.
