### ISSUE TITLE
Document allowed values for 'bundler'

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#27]
Right now I'm trying to figure out valid arguments for 'bundler'   The comment says 'windows.app' and 'jnlp'  but I don't know where those come from.  I'm looking at docs for javapackager '-native' argument and the fx:deploy ant task 'nativeBundles' attribute:
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html#sthref229
https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/javafx_ant_task_reference.html#CIABHEIG

... and see these values:
all
deb
dmg
exe
image
installer
mac.appStore
msi
none
pkg
rpm

I want to make an 'image' but bundler='image' doesn't work.

**Comment by FibreFoX** [comment]
There is no bundler called "imaged", these were bundler-categories, but they missed their real target. You have to specify your real bundler, if you really want to only run ONE bundler instead of all possible.

At the javafx-maven-plugin you could call `mvn jfx:list-bundlers`, to get all ids of the bundlers. That list is in change and depends on the installed JDK-version.
"all" is a special value for this plugin, other valid options are:
- jnlp
- (on **windows**) windows.app
- (on **windows**) windows.service (not in default list)
- (on **windows**) exe
- (on **windows**) msi
- (on **linux**) linux.app
- (on **linux**) deb
- (on **linux**) rpm
- (on **macosx**) mac.app
- (on **macosx**) mac.appStore
- (on **macosx**) mac.daemon (not in default list)
- (on **macosx**) dmg
- (on **macosx**) pkg

When looking into [the source-code of the bundlers](https://github.com/teamfx/openjfx-8u-dev-rt/tree/master/modules/fxpackager/src/main/java/com/oracle/tools/packager), you will find the IDs on the `public String getID()`-method of all `AbstractBundler`-implementing classes. Not all are loaded into the default-list, so you have to include them as customBundlers if not existing, but might not work.

**Comment by swpalmer** [comment]
So what is the equivalent of: javapackager -native image ?? Do I have to pick dynamically based on the platform?  I.e. windows.app is an image for Windows, linex.app is an image for Linux, etc..

**Comment by FibreFoX** [comment]
You don't have to specify any bundler, running out-of-the-box executes all bundler being possible on your system, so you can choose what to keep. As all bundlers might have their specific own bundleArguments, there won't be any support for that group-like option.

**Comment by swpalmer** [comment]
I don't want to waste the time creating things I won't use (e.g making the .msi is very slow).  I want to make the application image, tweak it with my own gradle tasks (e.g. add files), and then run my own tasks to make an installer or zip.
I have discovered that windows.app is what I want and I will dynamically pick the appropriate *.app bundler depending on the current platform.

**Comment by swpalmer** [comment]
Any idea when you might have the file-associations and additional-application-files examples ready?  I think with those I may be able to skip a lot of my custom gradle tasks and use the .msi that the plugin produces.

**Comment by FibreFoX** [comment]
You are right, when you only need one part of the bundlers, you need to pick the specific ".app"-packager for your buildsystem. This shouldn't be too hard to setup inside your buildscript, but please keep in mind, that these bundlers might have different options/bundleArguments, which control their behaviour.

Asking for any ETA on spare-time-projects, which I'm not getting paid for, is a bit of a no-no ;) I will try to tinker them a bit faster, don't expect them to be magic
