### ISSUE TITLE
jnlp bundler doesn't produce jnlp file and doesn't log any error/warning

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#42]
I have an application that is successfully bundling 'dmg' and 'pkg' bundles on OS X.  When I change the bundler to 'jnlp' there is no error, but all I get is an application image.  No .jnlp, no HTML files, no javascript, nothing.  The jfx configuration has verbose = true but nothing is printed for the jfxNative step.

E.g.:
$gradle clean jfxNative
:clean
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:jfxJar
:jfxNative

BUILD SUCCESSFUL

Total time: 2.944 secs
$ ls -R build/jfx
app

build/jfx/app:
ApplicationTemplate.jar lib

build/jfx/app/lib:
packager.jar

**Comment by FibreFoX** [comment]
What did `gradle clean jfxNative --info` say? For JNLP-files [it is required to have some bundleArguments](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/jnlp/JNLPBundler.java#L84) set up:
```groovy
jfx {
    // ...
    bundleArguments = [
        // ...
        'jnlp.outfile': 'my-fancy-application'
    ]
    // ...
}
```

Please don't hit the messenger (me) 😨 , I really don't know why this bundler does not take the application-name like all others do. Haven't opened an issue on the OpenJDK-project, because in the time this bundler has landed, it seemed too unfinished for me (it wasn't even some real bundler before the guys/gals ported that thing from the sun-package).

Would you feel better about it, when the plugin does some parameter-checking and warning, or do you prefer some auto-magic having the gradle-plugin set this `jnlp.outfile`-parameter with the appName?

**Comment by swpalmer** [comment]
It was the missing jnlp.outfile bundle argument. Thanks!

Some small amount of error checking would have helped.  Doing the auto-magic thing if the bundle argument is missing might be worth it.  Though I would log a warning maybe, just to point out that the plugin is "fixing" it for you.

**Comment by FibreFoX** [comment]
👍 good to hear it now is working for you, I will add this kind of "magic", with some parameter to disable it (like all the other stupid things I had to introduce)

**Comment by swpalmer** [comment]
Do you happen to have an example of using the jnlp bundler with signing?  Sadly it will happily produce a JNLP app that Java will refuse to run due to the security requirements.

**Comment by FibreFoX** [comment]
The builtin way for "signing" was something called "BLOB signing", but this never got integrated on other tools. Because of this, the upcoming JDK9 is going to DROP that support (very funny somehow):
https://bugs.openjdk.java.net/browse/JDK-8088866?focusedCommentId=13889898#comment-13889898

This even got reported on the [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/185), thats why I developed some way around this, signing (damn it ... I mistype that word so often ... it always ends up in "singing" :D ) using the `jarsigner`-tool.

You might want to try this setup (along with other settings):

```groovy
jfx {
    noBlobSigning = true
}
```

**Comment by FibreFoX** [comment]
@swpalmer did it work for you with `noBlobSigning`?

**Comment by FibreFoX** [comment]
ping @swpalmer

**Comment by FibreFoX** [comment]
Warning got added with commit https://github.com/FibreFoX/javafx-gradle-plugin/commit/65cef6dd24ab6207b6f1aec8866a39ec33daf0e9, this time without magic, because the developers should know what they are doing. Will be released after my commit was checked some times.

**Comment by swpalmer** [comment]
Sorry, I have had to switch away to something else for a while.  I believe it will work when I get the signing done properly, but I haven't had a chance to figure out how to do the signing with Gradle.  I was rather expecting the idea of producing a signed jar to be built-in.

**Comment by FibreFoX** [comment]
This is built-in within this plugin :) I will give you a example project tomorrow, maybe it's a bit lost inside this issue.
