### ISSUE TITLE
Is it possible to create Windows installer (.exe or .msi) which installs the app for all users?

### ISSUE THREAD

**Issue by radistao** [FibreFoX/javafx-gradle-plugin#46]
Hi, @FibreFoX.

Currently by default created Windows installer installs to `AppData` and may be used only by one system user. Is it possible to configure the plugin to install to `Program Files` for all users? (expecting to ask administrative privilege before installing)?

**Comment by FibreFoX** [comment]
Yes, it is possible by providing some bundleArguments:

```groovy
jfx{
    // ... other configuration
    bundleArguments = [
        // make "global" being default
        systemWide: true,
        // let user being able to choose installation-target
        installdirChooser: true
    ]
}
```

Can you confirm this working for you?

**Comment by radistao** [comment]
Tried: looks great! BUT: i can google it so far neither in your repo nor in maven-javafx plugin. Is it documented somewhere? If no, could we put this to the plugin doc/javadoc/README?
I could update and send you a pull request, if you wish

**Comment by FibreFoX** [comment]
This is a real ugly topic, because Oracle does not have any upated documentation, there are a lot of hidden switches and options, mostly inside each bundler. I am looking at them via [sourcecode](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinMsiBundler.java#l109).

I'm currently developing some new configuration-websites along with documentation about these things, but sadly I got sick last week. If this is fully implemented, you will get informed about this, mostly with some new repository containing that websites and via twitter. It often helps if you are searching through closed issues on both javafx-???-plugin projects.
