### ISSUE TITLE
Create fat-jar

### ISSUE THREAD

**Issue by zsolt-balanyi** [FibreFoX/javafx-gradle-plugin#51]
Hello!

Is there a possibility of creating a fat-jar, instead of having the dependencies in the lib folder?

BR, Zsolt

**Comment by FibreFoX** [comment]
Hi there,
short answer: NO!

It is not possible, because fat-jars have several problems. As this gradle plugin creates installers, there should not be any need to have fat-jars (it would get pretty awkward when having fat-jars with JNLPs). One mayor thing is it would remove some files which some jars are required, or imagine the situation where you are overwriting licences or property-files with different content.
