### ISSUE TITLE
javafx-grdle-plugin can't be configured due to wrong java.home

### ISSUE THREAD

**Issue by integrys-net** [FibreFoX/javafx-gradle-plugin#66]
Hi FibreFox, i'm finding this plugin very useful. But when configuring gradle project to use this plug-in, it can't be configured, throwing an exception about ant-javafx.jar library not found.
my JAVA_HOME environement variable correctly point to jdk install directory.
The JDK version installed in my machine is ```1.8.0_131 (Oracle Corporation 25.131-b11)```.

**Comment by FibreFoX** [comment]
This plugin utilizes the java-property "java.home", which is not the same as the JAVA_HOME environment property. Even on Maven there is a confusion about this, especially because Maven says that might me "java home": https://issues.apache.org/jira/browse/MNG-5756

Since the system property "java.home" returns the JRE from the current java-process, and as gradle has to run with the JDK, this returns the JRE inside the JDK. The path inside the javafx-gradle-plugin goes one folder an, which is the JDK-folder, and than into the lib-folder. Having this is everything that is needed.

If you have a problem with your local installation, this might be needed to get fixed by yourself. Otherwise please attache some project where I can reproduce your issue.

**Comment by integrys-net** [comment]
Thank you to have pointed me to right direction, i've thinked the problem concerned java home environment variable, but i'm wrong.
When using this plugin inside an eclipse project, eclipse during project configuration missing JAVA_HOME variable and the plugin thrown the exception.

Best regards
