### ISSUE TITLE
The output jar must be specified after an input jar, or it will be empty.

### ISSUE THREAD

**Issue by estebantcs** [FibreFoX/javafx-gradle-plugin#68]
Hi
i trying to use the gradle pluging with my javaFx to add Proguard. i have fallowed the example but i cant get it to work
. every time i run jfx jar or jfx Native get this error:

The output jar must be specified after an input jar, or it will be empty.

**Comment by FibreFoX** [comment]
Can you provide a project where I can help to debug? This is some message from proguard, maybe you have to change your build-file for this ... but I can't tell until I see that project.

**Comment by FibreFoX** [comment]
ping @estebantcs

**Comment by codecrafting-net** [comment]
I think I figure it out. First check name of the application jar of the file under `build\libs` directory, 
beacause it's not the same of `jfxMainAppJarName`, actually it is the `rootProject.name` on `settings.gradle`. Make sure that this name its on `injars` under your proguard task.

**Comment by FibreFoX** [comment]
Ah, I do understand now where the problem is! Thanks for clarifying this. Yes, the execution-order is the following:
* normal java-plugin creates some jar-file
* that created jar-file gets worked on with ProGuard
* that obfruscated proguard-jarfile gets picked up by the javafx-gradle-plugin.

When looking at the build-file I prepared inside the examples, I thought this was clear enough, will work on the examples the next day to clarify this a bit more. Thanks for reporting and sorry for these confusions.

@estebantcs is your question answered with this?
