### ISSUE TITLE
Running into "Couldn't find Ant-JavaFX-library" issue when using IntelliJ

### ISSUE THREAD

**Issue by Michael0x2a** [FibreFoX/javafx-gradle-plugin#79]
Hi -- 

I'm currently attempting to use your plugin with IntelliJ, using its Gradle plugin.

The plugin works beautifully when I run it from the command line, but fails with a "Couldn't find Ant-JavaFX-library" issue when running it as a Gradle task within IntelliJ.

The exact stacktrace thrown is quite long, so I've included it as a gist here: https://gist.github.com/Michael0x2a/1d966d7a61c13b552497008a688dde46

I've done a bit of debugging, and I suspect (though can't confirm) the issue is because IntelliJ returns a path to its internally bundled version of the JRE when you run `System.getProperty("java.home")` rather then to the path specified in the `JAVA_HOME` environment variable. This bundled version of Java doesn't seem to include the `ant-javafx.jar` file, unfortunately.

I realize that this is really more of an IntelliJ bug or an issue related to my personal setup rather then any problem with your plugin, but I wanted to ask here just in case you, or anybody else, knows of a workaround for this issue.

I've spent some time trying to adjust IntelliJ's settings to try and make `System.getProperty("java.home")` return the expected path, but no dice.

**Comment by FibreFoX** [comment]
Hi @Michael0x2a ,

I do know that problem already, this really is because of the bundled JDK of IntelliJ (as you suspected). Normally the bundled JDK is some OpenJDK without the OpenJFX-parts, this means you have to change your IDE to use the locally installed: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

The `java.home`-property is a special one and is NOT equivalent to JAVA_HOME, because this is the JRE inside the JDK, coming from Maven, this was a hard lesson to learn.

This is no bug of this plugin, but a configuration problem of your IDE.

**Comment by FibreFoX** [comment]
@Michael0x2a 
Is this stil an issue for you?

**Comment by sbrunk** [comment]
I'm currently running into this issues as well. Interestingly it works fine on my machine but not in our students lab, although their setup (Win10, Java8) is basically the same. @FibreFoX switching the IntelliJ JDK as you suggested works. I'm still trying to find the difference.

**Comment by FibreFoX** [comment]
@sbrunk thanks for that feedback :) it always is kinda funny to hear/read who is using this plugin, makes me a bit proud.

Don't know if this is some gradle-daemon-bug?! Maybe you could check (via process explorer by sysinternals), if there are processes between changing these settings. As I'm currently developing some replacement, this might disappear by "itself" :D

**Comment by sbrunk** [comment]
@FibreFoX well thanks to you for developing and maintaining the plugin! :)

I'll keep you posted if I can find the cause of the problem in case it isn't resolved by other means.
